import os

"""
This file is exists because i wanted to rename file, which is generated by midjourney.
Midjourney make very long name for images file, and this is very disturbing when i want to upload
image file on some websites, where there is limited file name length. I found midjourney usually 
include '-' between its name, so i split it and choose last element as new file name. And even there
is no '-', but still file name is long, that case also can be handled.
"""

def file_rename(file_name):
    if '-' in file_name:
        split_file_name = file_name.split('-')
        return split_file_name[-1]
    elif len(file_name) > 50:
        return file_name[:20]
    else:
        return file_name

def rename_files(directory):
    for filename in os.listdir(directory):
        old_file = os.path.join(directory, filename)
        new_file_name = file_rename(filename)
        new_file = os.path.join(directory, new_file_name)
        try :
            os.rename(old_file, new_file)    
            print("Source path renamed to destination path successfully.")
 
        # If Source is a file 
        # but destination is a directory
        except IsADirectoryError:
            print("Source is a file but destination is a directory.")
        
        # If source is a directory
        # but destination is a file
        except NotADirectoryError:
            print("Source is a directory but destination is a file.")
        
        # For permission related errors
        except PermissionError:
            print("Operation not permitted.")
        
        # For other errors
        except OSError as error:
            print(error)    


if __name__ ==  '__main__':
    print("file is now working.")
    directory = 'path/to/directory'
    rename_files(directory)
